# Generated by Django 5.2.7 on 2025-10-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0002_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('partial', 'Partially Filled'), ('done', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=10),
        ),
    ]
